class_name CellSprite

#const HIGHLIGHTS_LIST = [LEVEL1_ATTACK_HIGHLIGHT,LEVEL1_MOVE_HIGHLIGHT]
# Cell tile-set in the order of {Source:int,Atlas:Vector2i,Alternative:int}

#LEVEL 1
#cells
const LEVEL1_5HP = {"SOURCE":0,"ATLAS":Vector2i(0,0),"ALTERNATIVE":0, "HIGHLIGHT": false}
const LEVEL1_4HP = {"SOURCE":0,"ATLAS":Vector2i(1,0),"ALTERNATIVE":0, "HIGHLIGHT": false}
const LEVEL1_3HP = {"SOURCE":0,"ATLAS":Vector2i(2,0),"ALTERNATIVE":0, "HIGHLIGHT": false}
const LEVEL1_2HP = {"SOURCE":0,"ATLAS":Vector2i(3,0),"ALTERNATIVE":0, "HIGHLIGHT": false}
const LEVEL1_1HP = {"SOURCE":0,"ATLAS":Vector2i(4,0),"ALTERNATIVE":0, "HIGHLIGHT": false}

#Move highlight
const LEVEL1_MOVE_HIGHLIGHT_5HP = {"SOURCE":0,"ATLAS":Vector2i(0,1),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_MOVE_HIGHLIGHT_4HP = {"SOURCE":0,"ATLAS":Vector2i(1,1),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_MOVE_HIGHLIGHT_3HP = {"SOURCE":0,"ATLAS":Vector2i(2,1),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_MOVE_HIGHLIGHT_2HP = {"SOURCE":0,"ATLAS":Vector2i(3,1),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_MOVE_HIGHLIGHT_1HP = {"SOURCE":0,"ATLAS":Vector2i(4,1),"ALTERNATIVE":0, "HIGHLIGHT": true}

#Attack highlight
const LEVEL1_ATTACK_HIGHLIGHT_5HP = {"SOURCE":0,"ATLAS":Vector2i(0,2),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_ATTACK_HIGHLIGHT_4HP = {"SOURCE":0,"ATLAS":Vector2i(1,2),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_ATTACK_HIGHLIGHT_3HP = {"SOURCE":0,"ATLAS":Vector2i(2,2),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_ATTACK_HIGHLIGHT_2HP = {"SOURCE":0,"ATLAS":Vector2i(3,2),"ALTERNATIVE":0, "HIGHLIGHT": true}
const LEVEL1_ATTACK_HIGHLIGHT_1HP = {"SOURCE":0,"ATLAS":Vector2i(4,2),"ALTERNATIVE":0, "HIGHLIGHT": true}
